apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-LAS-APP
  labels:
    app: {{ .Release.Name }}-LAS-APP
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-LAS-APP
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-LAS-APP
    spec:
      containers:
      - name: {{ .Release.Name }}-LAS-APP
        image: docker.io/jocatalin/kubernetes-bootcamp:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-LAS-APP
  labels:
    app: {{ .Release.Name }}-LAS-APP
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-LAS-APP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing
spec:
  ingressClassName: nginx
  rules:
  - host: letsautomate.argocd.com
    http:
      paths:
      - path: /k8s
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-LAS-APP
            port:
              number: 8080